<a href="https://colab.research.google.com/github/Apollo355/movement-lab/blob/main/movement_lab_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
print("My robot journey starts here")


My robot journey starts here


In [8]:
print("My robot journey starts here")

My robot journey starts here


In [9]:
left_leg = [30, 60, 15]    # hip, knee, ankle
print(left_leg[0])
print(left_leg[1])


30
60


In [10]:
import numpy as np

left_leg = np.array([30, 60, 15])   # hip, knee, ankle
print(left_leg[1])
print(np.deg2rad(left_leg))

60
[0.52359878 1.04719755 0.26179939]


In [11]:
half_leg = left_leg * 0.5
print(half_leg)

[15.  30.   7.5]


In [12]:
import numpy as np

right_arm = np.array([90, 45, 10])   # shoulder, elbow, wrist (degrees)
print(right_arm[2])
print(right_arm * 2)

10
[180  90  20]


In [13]:
import numpy as np

# two frames of motion — the arm changing over time
# each ROW is one full pose: [shoulder, elbow, wrist]
motion = np.array([
    [90, 45, 10],    # frame 0
    [20, 30, 5]      # frame 1
])

print(motion)
print(motion[0])


[[90 45 10]
 [20 30  5]]
[90 45 10]
