<a href="https://colab.research.google.com/github/Apollo355/movement-lab/blob/main/movement_lab_lesson_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

start = np.array([0, 0, 0])     # shoulder, elbow, wrist — arm at rest
end   = np.array([90, 60, 30])  # target pose

motion = np.linspace(start, end, 4)   # whole arm, start → end, over 4 frames
print(motion)

[[ 0.  0.  0.]
 [30. 20. 10.]
 [60. 40. 20.]
 [90. 60. 30.]]
